#!/bin/bash
# /etc/init.d/cgminer

case "$1" in 
    start)
        echo "Starting cgminer"
	sleep 15
	cd /home/root/dualminer-cgminer
        ./cgminer  --api-listen  --scrypt  -c  /home/root/cgminer.conf.ltc -T &
	#sh test.sh -T &
          rm /home/root/.profile
        ;;
    stop)
        echo "Stopping cgminer"
        killall cgminer
        ;;

    *)
        echo "Usage: /etc/init.d/cgminer start|stop|restart"
        exit 1
        ;;
    
esac

exit 0


